package sgsi;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Luis Efe
 */
public class m_Hardware extends javax.swing.JFrame {

    /**
     * Creates new form activos_esenciales
     */
    public m_Hardware() {
        initComponents();
        this.setLocationRelativeTo(null);
        ;
        JPanel ocultar[] = AgregarRespuestas(respuesta27,respuesta28,respuesta29,respuesta30,respuesta31);
        for (int i = 0; i < ocultar.length; i++) {
            ocultar[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        Inferior = new javax.swing.JPanel();
        d6 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        Superior = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pregunta27 = new javax.swing.JPanel();
        gen27 = new javax.swing.JPanel();
        p27 = new javax.swing.JRadioButton();
        respuesta27 = new javax.swing.JPanel();
        cb79 = new javax.swing.JComboBox();
        cb80 = new javax.swing.JComboBox();
        cb81 = new javax.swing.JComboBox();
        pregunta28 = new javax.swing.JPanel();
        gen28 = new javax.swing.JPanel();
        p28 = new javax.swing.JRadioButton();
        respuesta28 = new javax.swing.JPanel();
        cb82 = new javax.swing.JComboBox();
        cb83 = new javax.swing.JComboBox();
        cb84 = new javax.swing.JComboBox();
        pregunta29 = new javax.swing.JPanel();
        gen29 = new javax.swing.JPanel();
        p29 = new javax.swing.JRadioButton();
        respuesta29 = new javax.swing.JPanel();
        cb85 = new javax.swing.JComboBox();
        cb86 = new javax.swing.JComboBox();
        cb87 = new javax.swing.JComboBox();
        pregunta30 = new javax.swing.JPanel();
        gen30 = new javax.swing.JPanel();
        p30 = new javax.swing.JRadioButton();
        respuesta30 = new javax.swing.JPanel();
        cb88 = new javax.swing.JComboBox();
        cb89 = new javax.swing.JComboBox();
        cb90 = new javax.swing.JComboBox();
        pregunta31 = new javax.swing.JPanel();
        gen31 = new javax.swing.JPanel();
        p31 = new javax.swing.JRadioButton();
        respuesta31 = new javax.swing.JPanel();
        cb91 = new javax.swing.JComboBox();
        cb92 = new javax.swing.JComboBox();
        cb93 = new javax.swing.JComboBox();

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Para más información sobre este módulo por favor dar un click ");

        jLabel3.setText("jLabel3");

        c6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("Por favor, no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar y evaluar\"");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Activos esenciales");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Inferior.setBackground(new java.awt.Color(173, 15, 55));

        d6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d6.setForeground(new java.awt.Color(255, 255, 255));
        d6.setText("Desarrollado por: Luis Fernando Díaz Muñoz - Juan Sebastián Erazo Chamorro");

        d10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d10.setForeground(new java.awt.Color(255, 255, 255));
        d10.setText("Ingeniería de sistemas UNICESMAG");

        javax.swing.GroupLayout InferiorLayout = new javax.swing.GroupLayout(Inferior);
        Inferior.setLayout(InferiorLayout);
        InferiorLayout.setHorizontalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d6)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d10)
                        .addGap(348, 348, 348))))
        );
        InferiorLayout.setVerticalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Superior.setBackground(new java.awt.Color(53, 96, 183));

        a.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("[Modulo Equipos informáticos (Hardware)]");

        b.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("y luego debe asignar valores entre 0 y 9  de acuerdo al conocimiento que tenga sobre los niveles de confidencialidad, integridad y disponibilidad de los mismos .");

        c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setText("Para continuar por favor no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar y evaluar\"");

        d.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setText("Nota: Para más información sobre los activos click en los signos de interrogación. Recuerde que (0) es el valor más bajo y (9) es el valor más alto de valoración. ");

        javax.swing.GroupLayout SuperiorLayout = new javax.swing.GroupLayout(Superior);
        Superior.setLayout(SuperiorLayout);
        SuperiorLayout.setHorizontalGroup(
            SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuperiorLayout.setVerticalGroup(
            SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c)
                .addGap(2, 2, 2)
                .addComponent(b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        d11.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d11.setText("Info (Click en etiquetas):");

        d12.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d12.setText("Confidencialidad ||");
        d12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d12MouseClicked(evt);
            }
        });

        d13.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d13.setText("Integridad ||");
        d13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d13MouseClicked(evt);
            }
        });

        d14.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d14.setText("Disponibilidad");
        d14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d14MouseClicked(evt);
            }
        });

        jButton1.setText("Comprobador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("activador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        p27.setText("[modem] Módems");
        p27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen27Layout = new javax.swing.GroupLayout(gen27);
        gen27.setLayout(gen27Layout);
        gen27Layout.setHorizontalGroup(
            gen27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen27Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen27Layout.setVerticalGroup(
            gen27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p27, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb79.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb79ActionPerformed(evt);
            }
        });

        cb80.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb80ActionPerformed(evt);
            }
        });

        cb81.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb81ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta27Layout = new javax.swing.GroupLayout(respuesta27);
        respuesta27.setLayout(respuesta27Layout);
        respuesta27Layout.setHorizontalGroup(
            respuesta27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb79, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb80, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb81, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta27Layout.setVerticalGroup(
            respuesta27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta27Layout = new javax.swing.GroupLayout(pregunta27);
        pregunta27.setLayout(pregunta27Layout);
        pregunta27Layout.setHorizontalGroup(
            pregunta27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta27Layout.setVerticalGroup(
            pregunta27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p28.setText("[hub] Concentradores");
        p28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen28Layout = new javax.swing.GroupLayout(gen28);
        gen28.setLayout(gen28Layout);
        gen28Layout.setHorizontalGroup(
            gen28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen28Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p28, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen28Layout.setVerticalGroup(
            gen28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p28, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb82.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb82ActionPerformed(evt);
            }
        });

        cb83.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb83ActionPerformed(evt);
            }
        });

        cb84.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb84ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta28Layout = new javax.swing.GroupLayout(respuesta28);
        respuesta28.setLayout(respuesta28Layout);
        respuesta28Layout.setHorizontalGroup(
            respuesta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb82, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb83, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb84, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta28Layout.setVerticalGroup(
            respuesta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta28Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta28Layout = new javax.swing.GroupLayout(pregunta28);
        pregunta28.setLayout(pregunta28Layout);
        pregunta28Layout.setHorizontalGroup(
            pregunta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta28Layout.setVerticalGroup(
            pregunta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta28Layout.createSequentialGroup()
                .addGroup(pregunta28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pregunta28Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gen28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pregunta28Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(respuesta28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        p29.setText("[switch] Conmutadores");
        p29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen29Layout = new javax.swing.GroupLayout(gen29);
        gen29.setLayout(gen29Layout);
        gen29Layout.setHorizontalGroup(
            gen29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen29Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p29, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen29Layout.setVerticalGroup(
            gen29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p29, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb85.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb85ActionPerformed(evt);
            }
        });

        cb86.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb86ActionPerformed(evt);
            }
        });

        cb87.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb87ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta29Layout = new javax.swing.GroupLayout(respuesta29);
        respuesta29.setLayout(respuesta29Layout);
        respuesta29Layout.setHorizontalGroup(
            respuesta29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb85, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb86, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb87, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta29Layout.setVerticalGroup(
            respuesta29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta29Layout = new javax.swing.GroupLayout(pregunta29);
        pregunta29.setLayout(pregunta29Layout);
        pregunta29Layout.setHorizontalGroup(
            pregunta29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta29Layout.setVerticalGroup(
            pregunta29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p30.setText("[router] Encaminadores");
        p30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen30Layout = new javax.swing.GroupLayout(gen30);
        gen30.setLayout(gen30Layout);
        gen30Layout.setHorizontalGroup(
            gen30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen30Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen30Layout.setVerticalGroup(
            gen30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p30, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb88.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb88ActionPerformed(evt);
            }
        });

        cb89.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb89ActionPerformed(evt);
            }
        });

        cb90.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb90ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta30Layout = new javax.swing.GroupLayout(respuesta30);
        respuesta30.setLayout(respuesta30Layout);
        respuesta30Layout.setHorizontalGroup(
            respuesta30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb88, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb89, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb90, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta30Layout.setVerticalGroup(
            respuesta30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta30Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta30Layout = new javax.swing.GroupLayout(pregunta30);
        pregunta30.setLayout(pregunta30Layout);
        pregunta30Layout.setHorizontalGroup(
            pregunta30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta30Layout.setVerticalGroup(
            pregunta30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta30Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p31.setText("[wap] Punto de acceso inalámbrico");
        p31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen31Layout = new javax.swing.GroupLayout(gen31);
        gen31.setLayout(gen31Layout);
        gen31Layout.setHorizontalGroup(
            gen31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen31Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen31Layout.setVerticalGroup(
            gen31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p31, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb91.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb91ActionPerformed(evt);
            }
        });

        cb92.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb92ActionPerformed(evt);
            }
        });

        cb93.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb93ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta31Layout = new javax.swing.GroupLayout(respuesta31);
        respuesta31.setLayout(respuesta31Layout);
        respuesta31Layout.setHorizontalGroup(
            respuesta31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb91, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb92, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb93, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta31Layout.setVerticalGroup(
            respuesta31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta31Layout = new javax.swing.GroupLayout(pregunta31);
        pregunta31.setLayout(pregunta31Layout);
        pregunta31Layout.setHorizontalGroup(
            pregunta31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta31Layout.setVerticalGroup(
            pregunta31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(d11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(pregunta27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta28, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta30, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta31, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d11)
                    .addComponent(d12)
                    .addComponent(d13)
                    .addComponent(d14)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /**
         * Activos.add (act1); Activos.add (act2); Activos.add (act3);
         * Activos.add (act4); Activos.add (act5); Activos.add (act6);
         * Activos.add (act7); Activos.add (act8); Activos.add (act9);
         */
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void d12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d12MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "La información no se pone a disposición ni se revela a individuos, entidades o procesos no autorizados.",
                "[Confidencialidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_d12MouseClicked

    private void d13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d13MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "Mantenimiento de la exactitud y completitud de la información y sus métodos de proceso.",
                "[Integridad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_d13MouseClicked

    private void d14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d14MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "Acceso y utilización de la información y los sistemas de tratamiento de la misma"
                + sl + "por parte de los individuos, entidades o procesos autorizados cuando lo requieran.",
                "[Disponibilidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_d14MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /*JRadioButton[] preguntas=new JRadioButton[4];
         preguntas=AgregarPreguntas(p1,p2,p4,p5);
         JPanel[] respuestas=new JPanel[4];
         pregunta4.setBounds(93, pregunta3.getY()+40, 544, 34);143 inicia
         respuestas=AgregarRespuestas(r2,r3,r4,r6);
         for (int i = 0; i < preguntas.length; i++) {
         if(preguntas[i].isSelected())respuestas[i].setVisible(false);
         }
         */
        JPanel[] controlador_preguntas = new JPanel[5];
        controlador_preguntas = Preguntas(pregunta27,pregunta28,pregunta29,pregunta30,pregunta31);
        JRadioButton[] preguntas = new JRadioButton[5];
        preguntas = AgregarPreguntas(p27,p28,p29,p30,p31);
        for (int i = 0; i < preguntas.length; i++) {
            if (!preguntas[i].isSelected()) {
                controlador_preguntas[i].setVisible(false);
            }
        }
        JPanel mostrar[] = AgregarRespuestas(respuesta27,respuesta28,respuesta29,respuesta30,respuesta31);
        for (int i = 0; i < mostrar.length; i++) {
            mostrar[i].setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList puntos = new ArrayList<String>();
        int controlar = 0;
        int inicio = 0;
        int finalizar = 2;
        String datos = "";
        JComboBox[] opciones = new JComboBox[15];
        opciones = respuestas(cb79,cb80,cb81,cb82,cb83,cb84,cb85,cb86,cb87,cb88,cb89,cb90,cb91,cb92,cb93);
        JRadioButton[] preguntas = new JRadioButton[5];
        preguntas = AgregarPreguntas(p27,p28,p29,p30,p31);
        for (int i = 0; i < preguntas.length; i++) {
            if (preguntas[i].isSelected()) {
                for (controlar = inicio; controlar <= finalizar; controlar++) {
                    datos = datos + opciones[controlar].getSelectedItem().toString() + "/";
                }
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            } else {
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            }
            if (datos != "") {
                puntos.add("grupo " + (i + 1) + "/activos " + (i + 1) + "/" + datos);
                datos = "";
            }

        }
        System.out.println(puntos);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p27ActionPerformed

    private void cb79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb79ActionPerformed

    private void cb80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb80ActionPerformed

    private void cb81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb81ActionPerformed

    private void p28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p28ActionPerformed

    private void cb82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb82ActionPerformed

    private void cb83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb83ActionPerformed

    private void cb84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb84ActionPerformed

    private void p29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p29ActionPerformed

    private void cb85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb85ActionPerformed

    private void cb86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb86ActionPerformed

    private void cb87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb87ActionPerformed

    private void p30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p30ActionPerformed

    private void cb88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb88ActionPerformed

    private void cb89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb89ActionPerformed

    private void cb90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb90ActionPerformed

    private void p31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p31ActionPerformed

    private void cb91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb91ActionPerformed

    private void cb92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb92ActionPerformed

    private void cb93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb93ActionPerformed

    public JRadioButton[] AgregarPreguntas(JRadioButton... arrayOpciones) {
        JRadioButton[] preguntas = new JRadioButton[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            preguntas[i] = arrayOpciones[i];
        }
        return preguntas;
    }

    public JPanel[] AgregarRespuestas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JPanel[] Preguntas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JComboBox[] respuestas(JComboBox... ArrayOpciones) {
        JComboBox[] res = new JComboBox[ArrayOpciones.length];
        for (int i = 0; i < ArrayOpciones.length; i++) {
            res[i] = ArrayOpciones[i];
        }
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m_Hardware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inferior;
    private javax.swing.JPanel Superior;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel c6;
    private javax.swing.JComboBox cb79;
    private javax.swing.JComboBox cb80;
    private javax.swing.JComboBox cb81;
    private javax.swing.JComboBox cb82;
    private javax.swing.JComboBox cb83;
    private javax.swing.JComboBox cb84;
    private javax.swing.JComboBox cb85;
    private javax.swing.JComboBox cb86;
    private javax.swing.JComboBox cb87;
    private javax.swing.JComboBox cb88;
    private javax.swing.JComboBox cb89;
    private javax.swing.JComboBox cb90;
    private javax.swing.JComboBox cb91;
    private javax.swing.JComboBox cb92;
    private javax.swing.JComboBox cb93;
    private javax.swing.JLabel d;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d6;
    private javax.swing.JPanel gen27;
    private javax.swing.JPanel gen28;
    private javax.swing.JPanel gen29;
    private javax.swing.JPanel gen30;
    private javax.swing.JPanel gen31;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton p27;
    private javax.swing.JRadioButton p28;
    private javax.swing.JRadioButton p29;
    private javax.swing.JRadioButton p30;
    private javax.swing.JRadioButton p31;
    private javax.swing.JPanel pregunta27;
    private javax.swing.JPanel pregunta28;
    private javax.swing.JPanel pregunta29;
    private javax.swing.JPanel pregunta30;
    private javax.swing.JPanel pregunta31;
    private javax.swing.JPanel respuesta27;
    private javax.swing.JPanel respuesta28;
    private javax.swing.JPanel respuesta29;
    private javax.swing.JPanel respuesta30;
    private javax.swing.JPanel respuesta31;
    // End of variables declaration//GEN-END:variables
}
