package sgsi;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Luis Efe
 */
public class m_Redes extends javax.swing.JFrame {

    /**
     * Creates new form activos_esenciales
     */
    public m_Redes() {
        initComponents();
        this.setLocationRelativeTo(null);
        ;
        JPanel ocultar[] = AgregarRespuestas(respuesta32, respuesta33,respuesta34,respuesta35,
                respuesta36,respuesta37,respuesta38,respuesta39);
        for (int i = 0; i < ocultar.length; i++) {
            ocultar[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        Inferior = new javax.swing.JPanel();
        d6 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        Superior = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pregunta32 = new javax.swing.JPanel();
        gen32 = new javax.swing.JPanel();
        p32 = new javax.swing.JRadioButton();
        respuesta32 = new javax.swing.JPanel();
        cb94 = new javax.swing.JComboBox();
        cb95 = new javax.swing.JComboBox();
        cb96 = new javax.swing.JComboBox();
        pregunta33 = new javax.swing.JPanel();
        gen33 = new javax.swing.JPanel();
        p33 = new javax.swing.JRadioButton();
        respuesta33 = new javax.swing.JPanel();
        cb97 = new javax.swing.JComboBox();
        cb98 = new javax.swing.JComboBox();
        cb99 = new javax.swing.JComboBox();
        pregunta34 = new javax.swing.JPanel();
        gen34 = new javax.swing.JPanel();
        p34 = new javax.swing.JRadioButton();
        respuesta34 = new javax.swing.JPanel();
        cb100 = new javax.swing.JComboBox();
        cb101 = new javax.swing.JComboBox();
        cb102 = new javax.swing.JComboBox();
        pregunta35 = new javax.swing.JPanel();
        gen35 = new javax.swing.JPanel();
        p35 = new javax.swing.JRadioButton();
        respuesta35 = new javax.swing.JPanel();
        cb103 = new javax.swing.JComboBox();
        cb104 = new javax.swing.JComboBox();
        cb105 = new javax.swing.JComboBox();
        pregunta36 = new javax.swing.JPanel();
        gen36 = new javax.swing.JPanel();
        p36 = new javax.swing.JRadioButton();
        respuesta36 = new javax.swing.JPanel();
        cb106 = new javax.swing.JComboBox();
        cb107 = new javax.swing.JComboBox();
        cb108 = new javax.swing.JComboBox();
        pregunta37 = new javax.swing.JPanel();
        gen37 = new javax.swing.JPanel();
        p37 = new javax.swing.JRadioButton();
        respuesta37 = new javax.swing.JPanel();
        cb109 = new javax.swing.JComboBox();
        cb110 = new javax.swing.JComboBox();
        cb111 = new javax.swing.JComboBox();
        pregunta38 = new javax.swing.JPanel();
        gen38 = new javax.swing.JPanel();
        p38 = new javax.swing.JRadioButton();
        respuesta38 = new javax.swing.JPanel();
        cb112 = new javax.swing.JComboBox();
        cb113 = new javax.swing.JComboBox();
        cb114 = new javax.swing.JComboBox();
        pregunta39 = new javax.swing.JPanel();
        gen39 = new javax.swing.JPanel();
        p39 = new javax.swing.JRadioButton();
        respuesta39 = new javax.swing.JPanel();
        cb115 = new javax.swing.JComboBox();
        cb116 = new javax.swing.JComboBox();
        cb117 = new javax.swing.JComboBox();

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Para más información sobre este módulo por favor dar un click ");

        jLabel3.setText("jLabel3");

        c6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("Por favor, no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar y evaluar\"");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Activos esenciales");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Inferior.setBackground(new java.awt.Color(173, 15, 55));

        d6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d6.setForeground(new java.awt.Color(255, 255, 255));
        d6.setText("Desarrollado por: Luis Fernando Díaz Muñoz - Juan Sebastián Erazo Chamorro");

        d10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d10.setForeground(new java.awt.Color(255, 255, 255));
        d10.setText("Ingeniería de sistemas UNICESMAG");

        javax.swing.GroupLayout InferiorLayout = new javax.swing.GroupLayout(Inferior);
        Inferior.setLayout(InferiorLayout);
        InferiorLayout.setHorizontalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d6)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d10)
                        .addGap(348, 348, 348))))
        );
        InferiorLayout.setVerticalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Superior.setBackground(new java.awt.Color(53, 96, 183));

        a.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("[Modulo Redes de comunicaciones]");

        b.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("y luego debe asignar valores entre 0 y 9  de acuerdo al conocimiento que tenga sobre los niveles de confidencialidad, integridad y disponibilidad de los mismos .");

        c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setText("Para continuar por favor no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar y evaluar\"");

        d.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setText("Nota: Para más información sobre los activos click en los signos de interrogación. Recuerde que (0) es el valor más bajo y (9) es el valor más alto de valoración. ");

        javax.swing.GroupLayout SuperiorLayout = new javax.swing.GroupLayout(Superior);
        Superior.setLayout(SuperiorLayout);
        SuperiorLayout.setHorizontalGroup(
            SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        SuperiorLayout.setVerticalGroup(
            SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c)
                .addGap(2, 2, 2)
                .addComponent(b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        d11.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d11.setText("Info (Click en etiquetas):");

        d12.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d12.setText("Confidencialidad ||");
        d12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d12MouseClicked(evt);
            }
        });

        d13.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d13.setText("Integridad ||");
        d13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d13MouseClicked(evt);
            }
        });

        d14.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d14.setText("Disponibilidad");
        d14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d14MouseClicked(evt);
            }
        });

        jButton1.setText("Comprobador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("activador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        p32.setText("[PSNT] Red telefónica");
        p32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen32Layout = new javax.swing.GroupLayout(gen32);
        gen32.setLayout(gen32Layout);
        gen32Layout.setHorizontalGroup(
            gen32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen32Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen32Layout.setVerticalGroup(
            gen32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p32, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb94.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb94ActionPerformed(evt);
            }
        });

        cb95.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb95ActionPerformed(evt);
            }
        });

        cb96.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb96ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta32Layout = new javax.swing.GroupLayout(respuesta32);
        respuesta32.setLayout(respuesta32Layout);
        respuesta32Layout.setHorizontalGroup(
            respuesta32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb94, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb95, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb96, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta32Layout.setVerticalGroup(
            respuesta32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta32Layout = new javax.swing.GroupLayout(pregunta32);
        pregunta32.setLayout(pregunta32Layout);
        pregunta32Layout.setHorizontalGroup(
            pregunta32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta32Layout.setVerticalGroup(
            pregunta32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p33.setText("[radio] Comunicaciones radio");
        p33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen33Layout = new javax.swing.GroupLayout(gen33);
        gen33.setLayout(gen33Layout);
        gen33Layout.setHorizontalGroup(
            gen33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen33Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p33, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen33Layout.setVerticalGroup(
            gen33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p33, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb97.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb97ActionPerformed(evt);
            }
        });

        cb98.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb98ActionPerformed(evt);
            }
        });

        cb99.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb99ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta33Layout = new javax.swing.GroupLayout(respuesta33);
        respuesta33.setLayout(respuesta33Layout);
        respuesta33Layout.setHorizontalGroup(
            respuesta33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb97, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb98, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb99, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta33Layout.setVerticalGroup(
            respuesta33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta33Layout = new javax.swing.GroupLayout(pregunta33);
        pregunta33.setLayout(pregunta33Layout);
        pregunta33Layout.setHorizontalGroup(
            pregunta33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pregunta33Layout.setVerticalGroup(
            pregunta33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p34.setText("[wifi] Red inalámbrica");
        p34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen34Layout = new javax.swing.GroupLayout(gen34);
        gen34.setLayout(gen34Layout);
        gen34Layout.setHorizontalGroup(
            gen34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen34Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen34Layout.setVerticalGroup(
            gen34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p34, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb100ActionPerformed(evt);
            }
        });

        cb101.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb101ActionPerformed(evt);
            }
        });

        cb102.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb102ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta34Layout = new javax.swing.GroupLayout(respuesta34);
        respuesta34.setLayout(respuesta34Layout);
        respuesta34Layout.setHorizontalGroup(
            respuesta34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb100, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb101, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb102, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta34Layout.setVerticalGroup(
            respuesta34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta34Layout = new javax.swing.GroupLayout(pregunta34);
        pregunta34.setLayout(pregunta34Layout);
        pregunta34Layout.setHorizontalGroup(
            pregunta34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta34Layout.setVerticalGroup(
            pregunta34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p35.setText("[mobile] Telefonía Móvil");
        p35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen35Layout = new javax.swing.GroupLayout(gen35);
        gen35.setLayout(gen35Layout);
        gen35Layout.setHorizontalGroup(
            gen35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen35Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen35Layout.setVerticalGroup(
            gen35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p35, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb103.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb103ActionPerformed(evt);
            }
        });

        cb104.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb104ActionPerformed(evt);
            }
        });

        cb105.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb105ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta35Layout = new javax.swing.GroupLayout(respuesta35);
        respuesta35.setLayout(respuesta35Layout);
        respuesta35Layout.setHorizontalGroup(
            respuesta35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb103, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb104, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb105, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta35Layout.setVerticalGroup(
            respuesta35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta35Layout = new javax.swing.GroupLayout(pregunta35);
        pregunta35.setLayout(pregunta35Layout);
        pregunta35Layout.setHorizontalGroup(
            pregunta35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta35Layout.setVerticalGroup(
            pregunta35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p36.setText("[sat] Por satélite");
        p36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen36Layout = new javax.swing.GroupLayout(gen36);
        gen36.setLayout(gen36Layout);
        gen36Layout.setHorizontalGroup(
            gen36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen36Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen36Layout.setVerticalGroup(
            gen36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p36, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb106.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb106ActionPerformed(evt);
            }
        });

        cb107.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb107ActionPerformed(evt);
            }
        });

        cb108.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb108ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta36Layout = new javax.swing.GroupLayout(respuesta36);
        respuesta36.setLayout(respuesta36Layout);
        respuesta36Layout.setHorizontalGroup(
            respuesta36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb106, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb107, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb108, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta36Layout.setVerticalGroup(
            respuesta36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta36Layout = new javax.swing.GroupLayout(pregunta36);
        pregunta36.setLayout(pregunta36Layout);
        pregunta36Layout.setHorizontalGroup(
            pregunta36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta36Layout.setVerticalGroup(
            pregunta36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p37.setText("[LAN] Red local");
        p37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen37Layout = new javax.swing.GroupLayout(gen37);
        gen37.setLayout(gen37Layout);
        gen37Layout.setHorizontalGroup(
            gen37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen37Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen37Layout.setVerticalGroup(
            gen37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p37, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb109.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb109ActionPerformed(evt);
            }
        });

        cb110.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb110ActionPerformed(evt);
            }
        });

        cb111.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb111ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta37Layout = new javax.swing.GroupLayout(respuesta37);
        respuesta37.setLayout(respuesta37Layout);
        respuesta37Layout.setHorizontalGroup(
            respuesta37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb109, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb110, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb111, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta37Layout.setVerticalGroup(
            respuesta37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta37Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta37Layout = new javax.swing.GroupLayout(pregunta37);
        pregunta37.setLayout(pregunta37Layout);
        pregunta37Layout.setHorizontalGroup(
            pregunta37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta37Layout.setVerticalGroup(
            pregunta37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta37Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p38.setText("[MAN] Red metropolitana");
        p38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen38Layout = new javax.swing.GroupLayout(gen38);
        gen38.setLayout(gen38Layout);
        gen38Layout.setHorizontalGroup(
            gen38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen38Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p38, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen38Layout.setVerticalGroup(
            gen38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p38, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb112.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb112ActionPerformed(evt);
            }
        });

        cb113.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb113ActionPerformed(evt);
            }
        });

        cb114.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb114ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta38Layout = new javax.swing.GroupLayout(respuesta38);
        respuesta38.setLayout(respuesta38Layout);
        respuesta38Layout.setHorizontalGroup(
            respuesta38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb112, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb113, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb114, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta38Layout.setVerticalGroup(
            respuesta38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta38Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta38Layout = new javax.swing.GroupLayout(pregunta38);
        pregunta38.setLayout(pregunta38Layout);
        pregunta38Layout.setHorizontalGroup(
            pregunta38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta38Layout.setVerticalGroup(
            pregunta38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta38Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p39.setText("[Internet] Internet");
        p39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p39ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen39Layout = new javax.swing.GroupLayout(gen39);
        gen39.setLayout(gen39Layout);
        gen39Layout.setHorizontalGroup(
            gen39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen39Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p39, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen39Layout.setVerticalGroup(
            gen39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p39, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb115.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb115ActionPerformed(evt);
            }
        });

        cb116.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb116ActionPerformed(evt);
            }
        });

        cb117.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb117ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta39Layout = new javax.swing.GroupLayout(respuesta39);
        respuesta39.setLayout(respuesta39Layout);
        respuesta39Layout.setHorizontalGroup(
            respuesta39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb115, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb116, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb117, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta39Layout.setVerticalGroup(
            respuesta39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta39Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb117, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pregunta39Layout = new javax.swing.GroupLayout(pregunta39);
        pregunta39.setLayout(pregunta39Layout);
        pregunta39Layout.setHorizontalGroup(
            pregunta39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pregunta39Layout.setVerticalGroup(
            pregunta39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta39Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pregunta32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta33, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta34, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta35, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta36, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta37, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta38, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta39, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(d11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(323, 323, 323))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d11)
                    .addComponent(d12)
                    .addComponent(d13)
                    .addComponent(d14)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /**
         * Activos.add (act1); Activos.add (act2); Activos.add (act3);
         * Activos.add (act4); Activos.add (act5); Activos.add (act6);
         * Activos.add (act7); Activos.add (act8); Activos.add (act9);
         */
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void d12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d12MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "La información no se pone a disposición ni se revela a individuos, entidades o procesos no autorizados.",
                "[Confidencialidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_d12MouseClicked

    private void d13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d13MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "Mantenimiento de la exactitud y completitud de la información y sus métodos de proceso.",
                "[Integridad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_d13MouseClicked

    private void d14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d14MouseClicked

        String sl = System.getProperty("line.separator");
        JOptionPane.showMessageDialog(rootPane, "Acceso y utilización de la información y los sistemas de tratamiento de la misma"
                + sl + "por parte de los individuos, entidades o procesos autorizados cuando lo requieran.",
                "[Disponibilidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_d14MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /*JRadioButton[] preguntas=new JRadioButton[4];
         preguntas=AgregarPreguntas(p1,p2,p4,p5);
         JPanel[] respuestas=new JPanel[4];
         pregunta4.setBounds(93, pregunta3.getY()+40, 544, 34);143 inicia
         respuestas=AgregarRespuestas(r2,r3,r4,r6);
         for (int i = 0; i < preguntas.length; i++) {
         if(preguntas[i].isSelected())respuestas[i].setVisible(false);
         }
         */
        JPanel[] controlador_preguntas = new JPanel[8];
        controlador_preguntas = Preguntas(pregunta32,pregunta33,pregunta34,pregunta35,pregunta36,
                pregunta37,pregunta38,pregunta39);
        JRadioButton[] preguntas = new JRadioButton[8];
        preguntas = AgregarPreguntas(p32,p33,p34,p35,p36,p37,p38,p39);
        for (int i = 0; i < preguntas.length; i++) {
            if (!preguntas[i].isSelected()) {
                controlador_preguntas[i].setVisible(false);
            }
        }
        JPanel mostrar[] = AgregarRespuestas(respuesta32, respuesta33,respuesta34,respuesta35,
                respuesta36,respuesta37,respuesta38,respuesta39);
        for (int i = 0; i < mostrar.length; i++) {
            mostrar[i].setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList puntos = new ArrayList<String>();
        int controlar = 0;
        int inicio = 0;
        int finalizar = 2;
        String datos = "";
        JComboBox[] opciones = new JComboBox[24];
        opciones = respuestas(cb94,cb95,cb96,cb97,cb98,cb99,cb100,cb101,cb102,cb103,cb104,cb105,cb106,cb107,cb108,cb109,cb110,
                cb111,cb112,cb113,cb114,cb115,cb116,cb117);
        JRadioButton[] preguntas = new JRadioButton[8];
        preguntas = AgregarPreguntas(p32,p33,p34,p35,p36,p37,p38,p39);
        for (int i = 0; i < preguntas.length; i++) {
            if (preguntas[i].isSelected()) {
                for (controlar = inicio; controlar <= finalizar; controlar++) {
                    datos = datos + opciones[controlar].getSelectedItem().toString() + "/";
                }
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            } else {
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            }
            if (datos != "") {
                puntos.add("grupo " + (i + 1) + "/activos " + (i + 1) + "/" + datos);
                datos = "";
            }

        }
        System.out.println(puntos);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p32ActionPerformed

    private void cb94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb94ActionPerformed

    private void cb95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb95ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb95ActionPerformed

    private void cb96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb96ActionPerformed

    private void p33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p33ActionPerformed

    private void cb97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb97ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb97ActionPerformed

    private void cb98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb98ActionPerformed

    private void cb99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb99ActionPerformed

    private void p34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p34ActionPerformed

    private void cb100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb100ActionPerformed

    private void cb101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb101ActionPerformed

    private void cb102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb102ActionPerformed

    private void p35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p35ActionPerformed

    private void cb103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb103ActionPerformed

    private void cb104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb104ActionPerformed

    private void cb105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb105ActionPerformed

    private void p36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p36ActionPerformed

    private void cb106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb106ActionPerformed

    private void cb107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb107ActionPerformed

    private void cb108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb108ActionPerformed

    private void p37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p37ActionPerformed

    private void cb109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb109ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb109ActionPerformed

    private void cb110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb110ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb110ActionPerformed

    private void cb111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb111ActionPerformed

    private void p38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p38ActionPerformed

    private void cb112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb112ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb112ActionPerformed

    private void cb113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb113ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb113ActionPerformed

    private void cb114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb114ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb114ActionPerformed

    private void p39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p39ActionPerformed

    private void cb115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb115ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb115ActionPerformed

    private void cb116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb116ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb116ActionPerformed

    private void cb117ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb117ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb117ActionPerformed

    public JRadioButton[] AgregarPreguntas(JRadioButton... arrayOpciones) {
        JRadioButton[] preguntas = new JRadioButton[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            preguntas[i] = arrayOpciones[i];
        }
        return preguntas;
    }

    public JPanel[] AgregarRespuestas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JPanel[] Preguntas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JComboBox[] respuestas(JComboBox... ArrayOpciones) {
        JComboBox[] res = new JComboBox[ArrayOpciones.length];
        for (int i = 0; i < ArrayOpciones.length; i++) {
            res[i] = ArrayOpciones[i];
        }
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m_Redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m_Redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m_Redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m_Redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m_Redes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inferior;
    private javax.swing.JPanel Superior;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel c6;
    private javax.swing.JComboBox cb100;
    private javax.swing.JComboBox cb101;
    private javax.swing.JComboBox cb102;
    private javax.swing.JComboBox cb103;
    private javax.swing.JComboBox cb104;
    private javax.swing.JComboBox cb105;
    private javax.swing.JComboBox cb106;
    private javax.swing.JComboBox cb107;
    private javax.swing.JComboBox cb108;
    private javax.swing.JComboBox cb109;
    private javax.swing.JComboBox cb110;
    private javax.swing.JComboBox cb111;
    private javax.swing.JComboBox cb112;
    private javax.swing.JComboBox cb113;
    private javax.swing.JComboBox cb114;
    private javax.swing.JComboBox cb115;
    private javax.swing.JComboBox cb116;
    private javax.swing.JComboBox cb117;
    private javax.swing.JComboBox cb94;
    private javax.swing.JComboBox cb95;
    private javax.swing.JComboBox cb96;
    private javax.swing.JComboBox cb97;
    private javax.swing.JComboBox cb98;
    private javax.swing.JComboBox cb99;
    private javax.swing.JLabel d;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d6;
    private javax.swing.JPanel gen32;
    private javax.swing.JPanel gen33;
    private javax.swing.JPanel gen34;
    private javax.swing.JPanel gen35;
    private javax.swing.JPanel gen36;
    private javax.swing.JPanel gen37;
    private javax.swing.JPanel gen38;
    private javax.swing.JPanel gen39;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton p32;
    private javax.swing.JRadioButton p33;
    private javax.swing.JRadioButton p34;
    private javax.swing.JRadioButton p35;
    private javax.swing.JRadioButton p36;
    private javax.swing.JRadioButton p37;
    private javax.swing.JRadioButton p38;
    private javax.swing.JRadioButton p39;
    private javax.swing.JPanel pregunta32;
    private javax.swing.JPanel pregunta33;
    private javax.swing.JPanel pregunta34;
    private javax.swing.JPanel pregunta35;
    private javax.swing.JPanel pregunta36;
    private javax.swing.JPanel pregunta37;
    private javax.swing.JPanel pregunta38;
    private javax.swing.JPanel pregunta39;
    private javax.swing.JPanel respuesta32;
    private javax.swing.JPanel respuesta33;
    private javax.swing.JPanel respuesta34;
    private javax.swing.JPanel respuesta35;
    private javax.swing.JPanel respuesta36;
    private javax.swing.JPanel respuesta37;
    private javax.swing.JPanel respuesta38;
    private javax.swing.JPanel respuesta39;
    // End of variables declaration//GEN-END:variables
}
