package sgsi;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Luis Efe
 */
public class m_Software extends javax.swing.JFrame {

    String sl = System.getProperty("line.separator");

    /**
     * Creates new form activos_esenciales
     */
    public m_Software() {
        initComponents();
        this.setLocationRelativeTo(null);
        ;
        JPanel ocultar[] = AgregarRespuestas(respuesta18, respuesta19, respuesta20, respuesta21,
                respuesta22, respuesta23, respuesta24, respuesta25);
        this.dispose();
        for (int i = 0; i < ocultar.length; i++) {
            ocultar[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        Info = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Inferior = new javax.swing.JPanel();
        d6 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        pregunta18 = new javax.swing.JPanel();
        gen18 = new javax.swing.JPanel();
        p18 = new javax.swing.JRadioButton();
        respuesta18 = new javax.swing.JPanel();
        cb52 = new javax.swing.JComboBox();
        cb53 = new javax.swing.JComboBox();
        cb54 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        pregunta19 = new javax.swing.JPanel();
        gen19 = new javax.swing.JPanel();
        p19 = new javax.swing.JRadioButton();
        respuesta19 = new javax.swing.JPanel();
        cb55 = new javax.swing.JComboBox();
        cb56 = new javax.swing.JComboBox();
        cb57 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        pregunta20 = new javax.swing.JPanel();
        gen20 = new javax.swing.JPanel();
        p20 = new javax.swing.JRadioButton();
        respuesta20 = new javax.swing.JPanel();
        cb58 = new javax.swing.JComboBox();
        cb59 = new javax.swing.JComboBox();
        cb60 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        pregunta21 = new javax.swing.JPanel();
        gen21 = new javax.swing.JPanel();
        p21 = new javax.swing.JRadioButton();
        respuesta21 = new javax.swing.JPanel();
        cb61 = new javax.swing.JComboBox();
        cb62 = new javax.swing.JComboBox();
        cb63 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        pregunta22 = new javax.swing.JPanel();
        gen22 = new javax.swing.JPanel();
        p22 = new javax.swing.JRadioButton();
        respuesta22 = new javax.swing.JPanel();
        cb64 = new javax.swing.JComboBox();
        cb65 = new javax.swing.JComboBox();
        cb66 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        pregunta23 = new javax.swing.JPanel();
        gen23 = new javax.swing.JPanel();
        p23 = new javax.swing.JRadioButton();
        respuesta23 = new javax.swing.JPanel();
        cb67 = new javax.swing.JComboBox();
        cb68 = new javax.swing.JComboBox();
        cb69 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        pregunta24 = new javax.swing.JPanel();
        gen24 = new javax.swing.JPanel();
        p24 = new javax.swing.JRadioButton();
        respuesta24 = new javax.swing.JPanel();
        cb70 = new javax.swing.JComboBox();
        cb71 = new javax.swing.JComboBox();
        cb72 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        pregunta25 = new javax.swing.JPanel();
        gen25 = new javax.swing.JPanel();
        p25 = new javax.swing.JRadioButton();
        respuesta25 = new javax.swing.JPanel();
        cb73 = new javax.swing.JComboBox();
        cb74 = new javax.swing.JComboBox();
        cb75 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        Ayuda = new javax.swing.JPanel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();
        Superior4 = new javax.swing.JPanel();
        a4 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Para más información sobre este módulo por favor dar un click ");

        jLabel3.setText("jLabel3");

        c6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("Por favor, no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar y evaluar\"");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soportes de información");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ítem");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("C");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("I");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("D");

        javax.swing.GroupLayout InfoLayout = new javax.swing.GroupLayout(Info);
        Info.setLayout(InfoLayout);
        InfoLayout.setHorizontalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(55, 55, 55)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        InfoLayout.setVerticalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)))
        );

        Inferior.setBackground(new java.awt.Color(173, 15, 55));

        d6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d6.setForeground(new java.awt.Color(255, 255, 255));
        d6.setText("Desarrollado por: Luis Fernando Díaz Muñoz - Juan Sebastián Erazo Chamorro");

        d10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d10.setForeground(new java.awt.Color(255, 255, 255));
        d10.setText("Ingeniería de sistemas UNICESMAG");

        javax.swing.GroupLayout InferiorLayout = new javax.swing.GroupLayout(Inferior);
        Inferior.setLayout(InferiorLayout);
        InferiorLayout.setHorizontalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d6)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                        .addComponent(d10)
                        .addGap(348, 348, 348))))
        );
        InferiorLayout.setVerticalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar y continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        p18.setText("[OS] Sistema operativo");
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen18Layout = new javax.swing.GroupLayout(gen18);
        gen18.setLayout(gen18Layout);
        gen18Layout.setHorizontalGroup(
            gen18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen18Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p18, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen18Layout.setVerticalGroup(
            gen18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p18, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb52.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb52ActionPerformed(evt);
            }
        });

        cb53.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb53ActionPerformed(evt);
            }
        });

        cb54.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb54ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta18Layout = new javax.swing.GroupLayout(respuesta18);
        respuesta18.setLayout(respuesta18Layout);
        respuesta18Layout.setHorizontalGroup(
            respuesta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb52, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb53, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb54, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta18Layout.setVerticalGroup(
            respuesta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel39.setText("¿?");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta18Layout = new javax.swing.GroupLayout(pregunta18);
        pregunta18.setLayout(pregunta18Layout);
        pregunta18Layout.setHorizontalGroup(
            pregunta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta18Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel39)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta18Layout.setVerticalGroup(
            pregunta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta18Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel39)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p19.setText("[Office] Ofimática");
        p19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen19Layout = new javax.swing.GroupLayout(gen19);
        gen19.setLayout(gen19Layout);
        gen19Layout.setHorizontalGroup(
            gen19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen19Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen19Layout.setVerticalGroup(
            gen19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p19, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb55.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb55ActionPerformed(evt);
            }
        });

        cb56.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb56ActionPerformed(evt);
            }
        });

        cb57.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb57ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta19Layout = new javax.swing.GroupLayout(respuesta19);
        respuesta19.setLayout(respuesta19Layout);
        respuesta19Layout.setHorizontalGroup(
            respuesta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb55, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb56, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb57, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta19Layout.setVerticalGroup(
            respuesta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel29.setText("¿?");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta19Layout = new javax.swing.GroupLayout(pregunta19);
        pregunta19.setLayout(pregunta19Layout);
        pregunta19Layout.setHorizontalGroup(
            pregunta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta19Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel29)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta19Layout.setVerticalGroup(
            pregunta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta19Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel29)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p20.setText("[www] Servidor de presentación");
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen20Layout = new javax.swing.GroupLayout(gen20);
        gen20.setLayout(gen20Layout);
        gen20Layout.setHorizontalGroup(
            gen20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen20Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen20Layout.setVerticalGroup(
            gen20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p20, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb58.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb58ActionPerformed(evt);
            }
        });

        cb59.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb59ActionPerformed(evt);
            }
        });

        cb60.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb60ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta20Layout = new javax.swing.GroupLayout(respuesta20);
        respuesta20.setLayout(respuesta20Layout);
        respuesta20Layout.setHorizontalGroup(
            respuesta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb58, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb59, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb60, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta20Layout.setVerticalGroup(
            respuesta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel30.setText("¿?");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta20Layout = new javax.swing.GroupLayout(pregunta20);
        pregunta20.setLayout(pregunta20Layout);
        pregunta20Layout.setHorizontalGroup(
            pregunta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta20Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel30)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta20Layout.setVerticalGroup(
            pregunta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta20Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel30)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p21.setText("[app] Servidor de aplicaciones");
        p21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen21Layout = new javax.swing.GroupLayout(gen21);
        gen21.setLayout(gen21Layout);
        gen21Layout.setHorizontalGroup(
            gen21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen21Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen21Layout.setVerticalGroup(
            gen21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p21, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb61.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb61ActionPerformed(evt);
            }
        });

        cb62.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb62ActionPerformed(evt);
            }
        });

        cb63.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb63ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta21Layout = new javax.swing.GroupLayout(respuesta21);
        respuesta21.setLayout(respuesta21Layout);
        respuesta21Layout.setHorizontalGroup(
            respuesta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb61, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb62, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb63, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta21Layout.setVerticalGroup(
            respuesta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel31.setText("¿?");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta21Layout = new javax.swing.GroupLayout(pregunta21);
        pregunta21.setLayout(pregunta21Layout);
        pregunta21Layout.setHorizontalGroup(
            pregunta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta21Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel31)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta21Layout.setVerticalGroup(
            pregunta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta21Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel31)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p22.setText("[email_client] Cliente de correo electrónico");
        p22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen22Layout = new javax.swing.GroupLayout(gen22);
        gen22.setLayout(gen22Layout);
        gen22Layout.setHorizontalGroup(
            gen22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen22Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen22Layout.setVerticalGroup(
            gen22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p22, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb64.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb64ActionPerformed(evt);
            }
        });

        cb65.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb65ActionPerformed(evt);
            }
        });

        cb66.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb66ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta22Layout = new javax.swing.GroupLayout(respuesta22);
        respuesta22.setLayout(respuesta22Layout);
        respuesta22Layout.setHorizontalGroup(
            respuesta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb64, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb65, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb66, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta22Layout.setVerticalGroup(
            respuesta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel32.setText("¿?");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta22Layout = new javax.swing.GroupLayout(pregunta22);
        pregunta22.setLayout(pregunta22Layout);
        pregunta22Layout.setHorizontalGroup(
            pregunta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta22Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel32)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta22Layout.setVerticalGroup(
            pregunta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta22Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel32)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p23.setText("[email_server] Servidor de correo electrónico");
        p23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen23Layout = new javax.swing.GroupLayout(gen23);
        gen23.setLayout(gen23Layout);
        gen23Layout.setHorizontalGroup(
            gen23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen23Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen23Layout.setVerticalGroup(
            gen23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p23, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb67.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb67ActionPerformed(evt);
            }
        });

        cb68.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb68ActionPerformed(evt);
            }
        });

        cb69.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb69ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta23Layout = new javax.swing.GroupLayout(respuesta23);
        respuesta23.setLayout(respuesta23Layout);
        respuesta23Layout.setHorizontalGroup(
            respuesta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb67, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb68, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb69, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta23Layout.setVerticalGroup(
            respuesta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel33.setText("¿?");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta23Layout = new javax.swing.GroupLayout(pregunta23);
        pregunta23.setLayout(pregunta23Layout);
        pregunta23Layout.setHorizontalGroup(
            pregunta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta23Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel33)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta23Layout.setVerticalGroup(
            pregunta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta23Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel33)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p24.setText("[Av] Antivirus");
        p24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen24Layout = new javax.swing.GroupLayout(gen24);
        gen24.setLayout(gen24Layout);
        gen24Layout.setHorizontalGroup(
            gen24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen24Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen24Layout.setVerticalGroup(
            gen24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p24, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb70.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb70ActionPerformed(evt);
            }
        });

        cb71.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb71ActionPerformed(evt);
            }
        });

        cb72.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb72ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta24Layout = new javax.swing.GroupLayout(respuesta24);
        respuesta24.setLayout(respuesta24Layout);
        respuesta24Layout.setHorizontalGroup(
            respuesta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb70, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb71, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb72, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta24Layout.setVerticalGroup(
            respuesta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel34.setText("¿?");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta24Layout = new javax.swing.GroupLayout(pregunta24);
        pregunta24.setLayout(pregunta24Layout);
        pregunta24Layout.setHorizontalGroup(
            pregunta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta24Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel34)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta24Layout.setVerticalGroup(
            pregunta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta24Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel34)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        p25.setText("[dbms] Sistema de gestión de bases de datos");
        p25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen25Layout = new javax.swing.GroupLayout(gen25);
        gen25.setLayout(gen25Layout);
        gen25Layout.setHorizontalGroup(
            gen25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen25Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        gen25Layout.setVerticalGroup(
            gen25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p25, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cb73.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb73ActionPerformed(evt);
            }
        });

        cb74.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb74ActionPerformed(evt);
            }
        });

        cb75.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bajo", "Medio", "Alto" }));
        cb75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb75ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout respuesta25Layout = new javax.swing.GroupLayout(respuesta25);
        respuesta25.setLayout(respuesta25Layout);
        respuesta25Layout.setHorizontalGroup(
            respuesta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respuesta25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb73, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb74, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb75, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        respuesta25Layout.setVerticalGroup(
            respuesta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, respuesta25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(respuesta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel35.setText("¿?");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pregunta25Layout = new javax.swing.GroupLayout(pregunta25);
        pregunta25.setLayout(pregunta25Layout);
        pregunta25Layout.setHorizontalGroup(
            pregunta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregunta25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respuesta25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pregunta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta25Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel35)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        pregunta25Layout.setVerticalGroup(
            pregunta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pregunta25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gen25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pregunta25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respuesta25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pregunta25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pregunta25Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel35)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pregunta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pregunta18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta23, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jScrollPane2.setViewportView(jPanel2);

        d11.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d11.setText("Info (Click en etiquetas):");

        d12.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d12.setText("Confidencialidad ||");
        d12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d12MouseClicked(evt);
            }
        });

        d13.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d13.setText("Integridad ||");
        d13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d13MouseClicked(evt);
            }
        });

        d14.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        d14.setText("Disponibilidad");
        d14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AyudaLayout = new javax.swing.GroupLayout(Ayuda);
        Ayuda.setLayout(AyudaLayout);
        AyudaLayout.setHorizontalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AyudaLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(d11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(d12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(d13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(d14)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        AyudaLayout.setVerticalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AyudaLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d11)
                        .addComponent(d12)
                        .addComponent(d13)
                        .addComponent(d14))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Superior4.setBackground(new java.awt.Color(53, 96, 183));

        a4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("[Modulo Aplicaciones (Software)]");

        b4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("y luego debe escoger entre (Bajo,Medio,Alto)  de acuerdo a los niveles de relevancia sobre la Confidencialidad (C), integridad (I) y disponibilidad (D) de los mismos .");

        c4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setText("Para continuar por favor no olvide que como paso inicial debe marcar los activos con los cuales cuente su organización, posteriormente dar click en \"Seleccionar\"");

        d4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        d4.setForeground(new java.awt.Color(255, 255, 255));
        d4.setText("Nota: Para más información sobre los activos click en los signos de interrogación disponibles en cada Ítem. ");

        javax.swing.GroupLayout Superior4Layout = new javax.swing.GroupLayout(Superior4);
        Superior4.setLayout(Superior4Layout);
        Superior4Layout.setHorizontalGroup(
            Superior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Superior4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Superior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a4)
                    .addComponent(b4)
                    .addComponent(c4)
                    .addComponent(d4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Superior4Layout.setVerticalGroup(
            Superior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Superior4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4)
                .addGap(2, 2, 2)
                .addComponent(b4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(Superior4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Superior4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /**
         * Activos.add (act1); Activos.add (act2); Activos.add (act3);
         * Activos.add (act4); Activos.add (act5); Activos.add (act6);
         * Activos.add (act7); Activos.add (act8); Activos.add (act9);
         */
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /*JRadioButton[] preguntas=new JRadioButton[4];
         preguntas=AgregarPreguntas(p1,p2,p4,p5);
         JPanel[] respuestas=new JPanel[4];
         pregunta4.setBounds(93, pregunta3.getY()+40, 544, 34);143 inicia
         respuestas=AgregarRespuestas(r2,r3,r4,r6);
         for (int i = 0; i < preguntas.length; i++) {
         if(preguntas[i].isSelected())respuestas[i].setVisible(false);
         }
         */
        JPanel[] controlador_preguntas = new JPanel[8];
        controlador_preguntas = Preguntas(pregunta18, pregunta19, pregunta20,
                pregunta21, pregunta22, pregunta23, pregunta24, pregunta25);
        JRadioButton[] preguntas = new JRadioButton[8];
        preguntas = AgregarPreguntas(p18, p19, p20, p21, p22, p23, p24, p25);
        for (int i = 0; i < preguntas.length; i++) {
            if (!preguntas[i].isSelected()) {
                controlador_preguntas[i].setVisible(false);
            }
        }
        JPanel mostrar[] = AgregarRespuestas(respuesta18, respuesta19, respuesta20, respuesta21,
                respuesta22, respuesta23, respuesta24, respuesta25);
        for (int i = 0; i < mostrar.length; i++) {
            mostrar[i].setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList puntos = new ArrayList<String>();
        int controlar = 0;
        int inicio = 0;
        int finalizar = 2;
        String datos = "";
        JComboBox[] opciones = new JComboBox[24];
        opciones = respuestas(cb52, cb53, cb54, cb55, cb56, cb57, cb58, cb59, cb60,
                cb61, cb62, cb63, cb64, cb65, cb66, cb67, cb68, cb69, cb70, cb71, cb72, cb73,
                cb74, cb75);
        JRadioButton[] preguntas = new JRadioButton[8];
        preguntas = AgregarPreguntas(p18, p19, p20, p21, p22, p23, p24, p25);
        for (int i = 0; i < preguntas.length; i++) {
            if (preguntas[i].isSelected()) {
                for (controlar = inicio; controlar <= finalizar; controlar++) {
                    datos = datos + opciones[controlar].getSelectedItem().toString() + "/";
                }
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            } else {
                inicio = finalizar + 1;
                finalizar = inicio + 2;
            }
            if (datos != "") {
                puntos.add("software" + (i + 1) + "/" + datos);
                datos = "";
            }

        }
        System.out.println(puntos);
        m_Arquitectura m = new m_Arquitectura();
        m.subir(puntos);
        volver();


    }//GEN-LAST:event_jButton2ActionPerformed
    public void volver() {
        Principal action = new Principal();
        action.setVisible(true);
        this.dispose();
    }
    private void p18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p18ActionPerformed

    private void cb52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb52ActionPerformed

    private void cb53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb53ActionPerformed

    private void cb54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb54ActionPerformed

    private void p19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p19ActionPerformed

    private void cb55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb55ActionPerformed

    private void cb56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb56ActionPerformed

    private void cb57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb57ActionPerformed

    private void p20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p20ActionPerformed

    private void cb58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb58ActionPerformed

    private void cb59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb59ActionPerformed

    private void cb60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb60ActionPerformed

    private void p21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p21ActionPerformed

    private void cb61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb61ActionPerformed

    private void cb62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb62ActionPerformed

    private void cb63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb63ActionPerformed

    private void p22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p22ActionPerformed

    private void cb64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb64ActionPerformed

    private void cb65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb65ActionPerformed

    private void cb66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb66ActionPerformed

    private void p23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p23ActionPerformed

    private void cb67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb67ActionPerformed

    private void cb68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb68ActionPerformed

    private void cb69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb69ActionPerformed

    private void p24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p24ActionPerformed

    private void cb70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb70ActionPerformed

    private void cb71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb71ActionPerformed

    private void cb72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb72ActionPerformed

    private void p25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p25ActionPerformed

    private void cb73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb73ActionPerformed

    private void cb74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb74ActionPerformed

    private void cb75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb75ActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked

        JOptionPane.showMessageDialog(rootPane, "La empresa u organización desarrollan sus propios sistemas con sus "
                + "programadores y analistas", "[prp] Desarrollo propio (in house)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Dispositivo de software que proporciona servicios de aplicaciones a las máquinas clientes", "[app] Servidor de aplicaciones", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Programa de computador usado para leer y enviar mensajes que son"
                + sl + " almacenados en la misma máquina donde se ejecutan", "[email_client] Cliente de correo electrónico", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Aplicación de red de computadores alojada en un servidor de internet"
                + sl + " para poder prestar el servicio de correo electrónico", "[email_server] Servidor de correo electrónico", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Permite el acceso remoto a los archivos que almacena o"
                + sl + " sobre los archivos a los cuales tiene acceso", "[file] Servidor de ficheros", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Programas que permiten el almacenamiento, modificación, y extracción de"
                + sl + " la información almacenada en una base de datos", "[dbms] Sistema de gestión de bases de datos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Software utilizado para navgar en la red de Internet", "[browser] Navegador web", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel39MouseClicked

    private void d12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d12MouseClicked

        JOptionPane.showMessageDialog(rootPane, "La información no se pone a disposición ni se revela a individuos, "
                + sl + "entidades o procesos no autorizados"
                + sl + ""
                + sl + "Valoración: ¿Qué daño causaría que lo conociera quién no debe?",
                "[Confidencialidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_d12MouseClicked

    private void d13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d13MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Mantenimiento de la exactitud y completitud de la información y sus"
                + sl + "métodos de proceso."
                + sl + ""
                + sl + "Valoración: ¿Qué perjuicio causaría qué estuviera dañado o corrupto?", "[Integridad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_d13MouseClicked

    private void d14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d14MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Acceso y utilización de la información y los sistemas de tratamiento de la misma"
                + sl + "por parte de los individuos, entidades o procesos autorizados cuando lo requieran "
                + sl + ""
                + sl + "Valoración: ¿Qué perjuicio causaría no tenerlo o no poder utilizarlo?",
                "[Disponibilidad]", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_d14MouseClicked

    public JRadioButton[] AgregarPreguntas(JRadioButton... arrayOpciones) {
        JRadioButton[] preguntas = new JRadioButton[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            preguntas[i] = arrayOpciones[i];
        }
        return preguntas;
    }

    public JPanel[] AgregarRespuestas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JPanel[] Preguntas(JPanel... arrayOpciones) {
        JPanel[] respuestas = new JPanel[arrayOpciones.length];
        for (int i = 0; i < arrayOpciones.length; i++) {
            respuestas[i] = arrayOpciones[i];
        }
        return respuestas;
    }

    public JComboBox[] respuestas(JComboBox... ArrayOpciones) {
        JComboBox[] res = new JComboBox[ArrayOpciones.length];
        for (int i = 0; i < ArrayOpciones.length; i++) {
            res[i] = ArrayOpciones[i];
        }
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m_Software().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ayuda;
    private javax.swing.JPanel Inferior;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel Superior4;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c6;
    private javax.swing.JComboBox cb52;
    private javax.swing.JComboBox cb53;
    private javax.swing.JComboBox cb54;
    private javax.swing.JComboBox cb55;
    private javax.swing.JComboBox cb56;
    private javax.swing.JComboBox cb57;
    private javax.swing.JComboBox cb58;
    private javax.swing.JComboBox cb59;
    private javax.swing.JComboBox cb60;
    private javax.swing.JComboBox cb61;
    private javax.swing.JComboBox cb62;
    private javax.swing.JComboBox cb63;
    private javax.swing.JComboBox cb64;
    private javax.swing.JComboBox cb65;
    private javax.swing.JComboBox cb66;
    private javax.swing.JComboBox cb67;
    private javax.swing.JComboBox cb68;
    private javax.swing.JComboBox cb69;
    private javax.swing.JComboBox cb70;
    private javax.swing.JComboBox cb71;
    private javax.swing.JComboBox cb72;
    private javax.swing.JComboBox cb73;
    private javax.swing.JComboBox cb74;
    private javax.swing.JComboBox cb75;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d6;
    private javax.swing.JPanel gen18;
    private javax.swing.JPanel gen19;
    private javax.swing.JPanel gen20;
    private javax.swing.JPanel gen21;
    private javax.swing.JPanel gen22;
    private javax.swing.JPanel gen23;
    private javax.swing.JPanel gen24;
    private javax.swing.JPanel gen25;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton p18;
    private javax.swing.JRadioButton p19;
    private javax.swing.JRadioButton p20;
    private javax.swing.JRadioButton p21;
    private javax.swing.JRadioButton p22;
    private javax.swing.JRadioButton p23;
    private javax.swing.JRadioButton p24;
    private javax.swing.JRadioButton p25;
    private javax.swing.JPanel pregunta18;
    private javax.swing.JPanel pregunta19;
    private javax.swing.JPanel pregunta20;
    private javax.swing.JPanel pregunta21;
    private javax.swing.JPanel pregunta22;
    private javax.swing.JPanel pregunta23;
    private javax.swing.JPanel pregunta24;
    private javax.swing.JPanel pregunta25;
    private javax.swing.JPanel respuesta18;
    private javax.swing.JPanel respuesta19;
    private javax.swing.JPanel respuesta20;
    private javax.swing.JPanel respuesta21;
    private javax.swing.JPanel respuesta22;
    private javax.swing.JPanel respuesta23;
    private javax.swing.JPanel respuesta24;
    private javax.swing.JPanel respuesta25;
    // End of variables declaration//GEN-END:variables
}
